---
- name: Add Docker CE Stable repository
  yum_repository:
    name: docker-ce
    description: Docker Community Edition Stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present

- name: Install Docker CE
  dnf:
    name: docker-ce
    state: present

- name: Docker directory should exist
  file:
    path: /etc/docker
    state: directory

- name: Make sure Docker uses systemd cgroupdriver
  copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
