---
- hosts: all
  become: yes
  roles:
    - { role: 'docker-ce', tags: docker }
    - { role: 'kubernetes', tags: kubernetes }

- hosts: cp
  vars:
    pod_network_cidr: '10.244.0.0/16'
    api_advertise_addr: "{{ ansible_enp0s3.ipv4.address }}"
    # Flannel manifest also bundles RBAC permissions.
    network_plugin_manifest: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  tasks:
    - name: Intializing Kubernetes Control Plane
      command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}" --apiserver-advertise-address "{{ api_advertise_addr }}"
      become: yes
      run_once: yes

    - name: Create directory for Kubernetes config
      file:
       path: /home/{{ ansible_user }}/.kube
       state: directory

    - name: Copy Kubernetes admin conf to config dir
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Initialize network plugin
      command: kubectl apply -f {{ network_plugin_manifest }}

    - name: Get join command
      shell: kubeadm token create  --print-join-command 
      register: cluster_join_command

- hosts: workers
  become: true
  tasks: 
    - name: Join the cluster
      command: "sh {{ hostvars['tengu']['cluster_join_command'] }}"
